laptops/urls.py
from django.urls import path
from laptops.views import*
app_name='laptops'

urlpatterns=[
    path('dell/',dell,name='dell'),
]

project9/urls.py
from django.contrib import admin
from django.urls import path,include
import laptops
from phones.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('laptops/',include('laptops.urls')),
    path('vivo/',vivo,name='vivo'),

]

laptops/models.py
from django.db import models

# Create your models here.

phones/models.py
from django.db import models

# Create your models here.

laptops/views.py
from django.shortcuts import render

# Create your views here.
def dell(request):
    return render(request,'dell.html')

phones/views.py
from django.shortcuts import render

# Create your views here.
def vivo(request):
    return render(request,'vivo.html')

templates/dell.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="background-color: hotpink;">
    <center>
    <h1>LAPTOPS PAGE</h1>
    <h2><a href="{% url 'vivo' %}">navigating to phones page</a></h2>
</center>
    
</body>
</html>

templates/vivo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="background-color: greenyellow;">
    <center>
        <h1>PHONES PAGE</h1>
        <h2><a href="{% url 'laptops:dell' %}">navigating to laptops</a></h2>
    </center>
    
</body>
</html>